### ISSUE TITLE
Mods not working

### ISSUE THREAD

**Issue by Gengar-lab** [MattZ45986/Bombsquad_mods#3]
@MattZ45986 I can't play any of the mod , please make a link to download them,hence I would be able to play them.

I have some ideas,why don't you create powerups to use in original bombsquad that would be able to use in Multiplayer Teams.

**Comment by ghost** [comment]
Hello @Benefit-Zebra Mods works fine, can you tell how do you download the mods.

I made issue page where you can suggest ideas for mods on https://github.com/MattZ45986/Bombsquad_mods/issues/2

2 Ways to Download Mods :

1. One by One. Just click the mod file (.PY) and find the RAW button. After that download the page, in Chrome you should be able to download the websites. It automatically downloads the .PY or mod file. Both Android and PC Chrome works.

2. All. If you are tired of downloading the mods one by one and wants to try it all, you can just download it in .ZIP file. https://github.com/MattZ45986/Bombsquad_mods/archive/master.zip

I prefer downloading in One by One, since the author @MattZ45986 makes some changes and updates the mods.

**Comment by MattZ45986** [comment]
@Benefit-Zebra , I'm not sure what you mean by powerups for the original bombsquad.  I can make new powerups, but could you be a bit more specific? Thanks.

**Comment by Gengar-lab** [comment]
Hii @Esie-Eyen Your First method is not working on my android.Thanks for your second method.

@MattZ45986 The Spaz In "SimonSays" and "Jumping Contest" does not spawn,please edit the mod.

**Comment by ghost** [comment]
@Benefit-Zebra Can you give me the exact file size of the SimonSays.py and JumpingContest.py . Im not sure why those mods are not working for you, give me the KB size.

I have the same problem but the author @MattZ45986 already fix the mods. See it on https://github.com/MattZ45986/Bombsquad_mods/issues/1

KB SIZES : 
- SimonSays.py (8.54KB)
- JumpingContest.py (7.45KB)

Number 1 should work fine in downloading mods :
1.Find the .PY file you like
2.Find the RAW button (Make it in Desktop Mode for Android)
3.Click the 3 dots on the top-right or settings
4.There should be a download button
5.Thats all.

**Comment by Gengar-lab** [comment]
@Esie-Eyen
KB Sizes:

● SimonSays.py (8.46KB)

● Jumping Contest.py (7.32KB)

Thanks Now your Method is working.

**Comment by Gengar-lab** [comment]
Can anyone tell how can I capture Flag in Siege.py ?

**Comment by ghost** [comment]
@Benefit-Zebra What do you mean? You just need to go inside the puck wall and grab the flag. It should make you the winner.

**Comment by Gengar-lab** [comment]
@Esie-Eyen But there is no space to enter inside the puck wall?

**Comment by MattZ45986** [comment]
@Benefit-Zebra , you have to figure out how to get inside using the powerups. It's a puzzle of sorts.

**Comment by Benefit-Zebra** [comment]
@MattZ45986

In "MusicalFlags.py" instead of Flag unlimited number of players are spawn when a player dies.

**Comment by Gengar-lab** [comment]
@MattZ45986

In "MusicalFlags.py" instead of Flag unlimited number of players are spawn when a player dies.

**Comment by MattZ45986** [comment]
I'm still testing Musical Flags, @Benefit-Zebra.  I'll tell you when I'm done with it.

**Comment by Gengar-lab** [comment]
@MattZ45986

I will wait.
