### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Gengar-lab** [MattZ45986/Bombsquad_mods#6]
@MattZ45986

When I try to get portal powerup , I pass through it and powerup is not taken.

Please solve this problem.

**Comment by MattZ45986** [comment]
Alright.  To get a few things straight: 

1. This is not the place to be discussing the portal powerup. The powerup isn't even in this repository.
2. I did not make the powerup.  In the future, ask @I-Am-The-Great. 
3. It is generally a good idea to thoroughly test something before writing about a problem.  The powerup obviously works for those of us who have tested it, so it is good etiquette to make sure the issue isn't on your end first.

Now, to reply to your issue the best I can, there might be a problem with your snowyPowerup.py file.  Make sure it is updated because the portal relies on that file as well as the Portal.py script.  If it is in fact updated, when you are playing and you encounter the issue, I want you to send me the error from the console.  That will give me a better idea of what is going on.  To get to the console, on PC, press the (  `  ) button (which is usually in the top-left).

Hope that helps, but I would appreciate it if we continue this chat in the actual mod-manager, where others can learn from this.  It will also give @I-Am-The-Great an opportunity to chime in.
